import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import { PATHS } from "@/constants/paths";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}
        <nav className="flex justify-between py-2.5 px-5 border-b-2 w-full backdrop-blur-2xl bg-amber-100/95
        fixed left-0 right-0 top-0 z-20">
        <div>
          <Link href={PATHS.HOME} className="text-bold text-lg">Home</Link>
        </div>
        <div>
          <Link href={PATHS.TICKETS} className="text-sm underline">Tickets</Link>
        </div>
      </nav>
      </body>
    </html>
  );
}
